classifier: 'qda'
KFold:
  n_folds: 10
classification:
  individual: True
  combinations: True
  save_all_results: True
  save_summary_file: True
svm_config:
  fine_tuning_svm: True
  kernel_svm: 'linear' # if fine_tuning = False
  C_value: 1.0         # if fine_tuning = False
filepaths:
  dataset_path: "D:\\programming\\classification\\medidas2.csv"
  results_path: "D:\\programming\\classification"
dataset:
  label_column: "CLASS_NUM"
  number_of_metrics: 10 # last 10 columns of your dataset
  combos: 'all' # alternatively, chose a list of numbers, e.g., [2,3,4,5]
parallelism: False