def print_classifier(classifier):
    if classifier == "qda":
        print("    _______        __________             ___          ")
        print("   /       \      |          \           /   \         ")
        print("  /   ____  \     |   _____   \         /     \        ")
        print(" /   /    \  \    |  |     \   |       /   _   \       ")
        print("|   /      \  |   |  |      |  |      /   / \   \      ")
        print("|   | _____ | |   |  |      |  |     /   /___\   \     ")
        print("|   \/ __  \| |   |  |      |  |    /             \    ")
        print(" \   \/__\  \_/_  |  |_____/   |   /     _____     \   ")
        print("  \       \_____| |            /  /     /     \     \  ")
        print("   \_______/      |___________/  /_____/       \_____\ ")
        print("CLASSIFIER PIPELINE")

    elif classifier == "lda":
        print(" ___             __________             ___          ")
        print("|   |           |          \           /   \         ")
        print("|   |           |   _____   \         /     \        ")
        print("|   |           |  |     \   |       /   _   \       ")
        print("|   |           |  |      |  |      /   / \   \      ")
        print("|   |           |  |      |  |     /   /___\   \     ")
        print("|   |           |  |      |  |    /             \    ")
        print("|   |__________ |  |_____/   |   /     _____     \   ")
        print("|              ||            /  /     /     \     \  ")
        print("|______________||___________/  /_____/       \_____\ ")
        print("CLASSIFIER PIPELINE")

    elif classifier == "svm":
        print("  ____________  ____              ____  ___          ___   ")
        print(" /            | \   \            /   / |   \        /   |  ")
        print("|     _______/   \   \          /   /  |    \      /    |  ")
        print("|     \______     \   \        /   /   |     \    /     |  ")
        print(" \            \    \   \      /   /    |      \  /      |  ")
        print("  \ _______    |    \   \    /   /     |       \/       |  ")
        print("           |   |     \   \  /   /      |   |\      /|   |  ")
        print("  ________/    |      \   \/   /       |   | \    / |   |  ")
        print(" /             |       \      /        |   |  \__/  |   |  ")
        print("/_____________/         \____/         |___|        |___|  ")
        print("CLASSIFIER PIPELINE")